In [157]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

In [158]:
df = pd.read_csv("BostonHousing.csv")
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [159]:
data_ = df.loc[:,['age','lstat','medv']]
data_

age  lstat  medv
0    65.2   4.98  24.0
1    78.9   9.14  21.6
2    61.1   4.03  34.7
3    45.8   2.94  33.4
4    54.2   5.33  36.2
..    ...    ...   ...
501  69.1   9.67  22.4
502  76.7   9.08  20.6
503  91.0   5.64  23.9
504  89.3   6.48  22.0
505  80.8   7.88  11.9

[506 rows x 3 columns]

In [160]:
X = pd.DataFrame(data_.iloc[:,:-1])
y = pd.DataFrame(data_.iloc[:,-1])

In [161]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=16)

In [162]:
scaler = StandardScaler()
# Fit trên tập huấn luyện
scaler.fit(X_train)

# Transform cả hai tập
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [163]:
model = LinearRegression()
model.fit(X_train_scaled,y_train)

LinearRegression()

In [164]:
y_pred = model.predict(X_test_scaled)

In [165]:
print(f"MAPE: {mean_absolute_percentage_error(y_test,y_pred)}")
print(f"R2: {r2_score(y_test,y_pred)}")

MAPE: 0.2547803169337024
R2: 0.4069676937197575


In [166]:
y_pred

array([[30.30177452],
       [12.02736106],
       [ 2.89687335],
       [28.46456642],
       [21.87864437],
       [23.53637856],
       [23.42561427],
       [16.79514925],
       [19.44271064],
       [32.45858113],
       [17.09757538],
       [11.84622391],
       [12.36285788],
       [26.40957339],
       [-5.08197079],
       [25.4099039 ],
       [25.86495849],
       [30.86874755],
       [20.07279705],
       [16.13836531],
       [27.00512045],
       [20.97599859],
       [ 7.05717046],
       [-0.91645467],
       [14.29925007],
       [21.67691765],
       [ 8.48179584],
       [20.94550809],
       [15.74149566],
       [ 6.13021011],
       [24.43977734],
       [25.91093946],
       [-3.93645386],
       [ 8.24768081],
       [10.80636953],
       [27.47735675],
       [21.0118254 ],
       [15.96545652],
       [30.40170227],
       [19.85525602],
       [27.0623298 ],
       [29.92677784],
       [28.74759446],
       [15.77748905],
       [20.47771915],
       [27

In [167]:
X_train_scaled

array([[ 9.07429286e-01,  8.93808981e-01],
       [-2.14941699e+00, -7.74104371e-01],
       [-1.62396606e+00, -5.22593628e-01],
       [-6.89153427e-02, -1.03002758e+00],
       [-9.45850336e-01, -1.18152236e+00],
       [-5.05607667e-01, -1.12233993e-01],
       [-1.20147511e+00,  3.18717164e-01],
       [-4.55902850e-01, -8.87008245e-02],
       [ 3.50025261e-01, -7.31450503e-01],
       [-1.27958268e+00, -8.40291409e-01],
       [ 3.75949804e-02, -3.38740745e-01],
       [-1.47022913e-01, -3.75511322e-01],
       [ 1.10269821e+00,  7.32018444e-01],
       [-3.67144247e-01, -5.21122805e-01],
       [-6.79574529e-01, -3.47565683e-01],
       [-2.14231630e+00, -1.24329693e+00],
       [-1.17307236e+00, -1.16240166e+00],
       [ 1.22803239e-01,  3.11363048e-01],
       [-8.78393798e-01, -3.69628029e-01],
       [-1.40029438e+00, -8.27054002e-01],
       [ 6.66005887e-01,  7.52609967e-01],
       [ 9.35832039e-01,  7.23193506e-01],
       [ 3.14521820e-01, -1.14328096e+00],
       [ 8.

In [168]:
slope = model.coef_[0]
intercept = model.intercept_

print(f"Hệ số góc: {slope}")
print(f"Hệ số chặn: {intercept}")

Hệ số góc: [ 1.62128474 -7.86694092]
Hệ số chặn: [23.09579208]


In [169]:
print(X_train.shape)

(404, 2)


In [170]:
y_train

medv
488  15.2
70   24.2
53   23.4
0    24.0
57   31.6
..    ...
321  23.1
69   20.9
121  20.3
238  23.7
169  22.3

[404 rows x 1 columns]

In [178]:
X_train

age  lstat
488  92.7  18.06
70    6.6   6.72
53   21.4   8.43
0    65.2   4.98
57   40.5   3.95
..    ...    ...
321  54.3   6.87
69   33.0   8.79
121  84.1  14.27
238  18.5   6.36
169  95.2  11.32

[404 rows x 2 columns]

In [171]:
X_train_scaled

array([[ 9.07429286e-01,  8.93808981e-01],
       [-2.14941699e+00, -7.74104371e-01],
       [-1.62396606e+00, -5.22593628e-01],
       [-6.89153427e-02, -1.03002758e+00],
       [-9.45850336e-01, -1.18152236e+00],
       [-5.05607667e-01, -1.12233993e-01],
       [-1.20147511e+00,  3.18717164e-01],
       [-4.55902850e-01, -8.87008245e-02],
       [ 3.50025261e-01, -7.31450503e-01],
       [-1.27958268e+00, -8.40291409e-01],
       [ 3.75949804e-02, -3.38740745e-01],
       [-1.47022913e-01, -3.75511322e-01],
       [ 1.10269821e+00,  7.32018444e-01],
       [-3.67144247e-01, -5.21122805e-01],
       [-6.79574529e-01, -3.47565683e-01],
       [-2.14231630e+00, -1.24329693e+00],
       [-1.17307236e+00, -1.16240166e+00],
       [ 1.22803239e-01,  3.11363048e-01],
       [-8.78393798e-01, -3.69628029e-01],
       [-1.40029438e+00, -8.27054002e-01],
       [ 6.66005887e-01,  7.52609967e-01],
       [ 9.35832039e-01,  7.23193506e-01],
       [ 3.14521820e-01, -1.14328096e+00],
       [ 8.

In [172]:
v = pd.DataFrame(model.coef_, index=['Co_ef']).transpose()
w = pd.DataFrame(X.columns, columns=['Atrribute'])

coef_df = pd.concat([w,v], axis=1, join='inner')
coef_df

Atrribute     Co_ef
0       age  1.621285
1     lstat -7.866941

In [174]:
model.coef_

array([[ 1.62128474, -7.86694092]])

In [173]:
age_value = 37.5
lstat_value = 4.65
X_new = np.array([[age_value, lstat_value]])
predicted_medv = model.predict(X_new)

print("Dự đoán giá trị medv:", predicted_medv[0])

Dự đoán giá trị medv: [47.31269472]


In [175]:
X_train_scaled

array([[ 9.07429286e-01,  8.93808981e-01],
       [-2.14941699e+00, -7.74104371e-01],
       [-1.62396606e+00, -5.22593628e-01],
       [-6.89153427e-02, -1.03002758e+00],
       [-9.45850336e-01, -1.18152236e+00],
       [-5.05607667e-01, -1.12233993e-01],
       [-1.20147511e+00,  3.18717164e-01],
       [-4.55902850e-01, -8.87008245e-02],
       [ 3.50025261e-01, -7.31450503e-01],
       [-1.27958268e+00, -8.40291409e-01],
       [ 3.75949804e-02, -3.38740745e-01],
       [-1.47022913e-01, -3.75511322e-01],
       [ 1.10269821e+00,  7.32018444e-01],
       [-3.67144247e-01, -5.21122805e-01],
       [-6.79574529e-01, -3.47565683e-01],
       [-2.14231630e+00, -1.24329693e+00],
       [-1.17307236e+00, -1.16240166e+00],
       [ 1.22803239e-01,  3.11363048e-01],
       [-8.78393798e-01, -3.69628029e-01],
       [-1.40029438e+00, -8.27054002e-01],
       [ 6.66005887e-01,  7.52609967e-01],
       [ 9.35832039e-01,  7.23193506e-01],
       [ 3.14521820e-01, -1.14328096e+00],
       [ 8.